# Generated by Django 4.2.1 on 2023-05-28 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0002_accountmodel_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='token',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a163150-6c39-4904-9202-7c9606f12c11'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
